### PR TITLE
prometheus monitoring fix - missing label

### PR DESCRIPTION
**Pull request by Kris686**
### Issue description

Pulumi kubernetes operator creates Service and ServiceMonitor objects for metrics by itself:
https://github.com/pulumi/pulumi-kubernetes-operator/blob/7d9e693bc6e27f1e3881ce350cdf7fbde71b26be/cmd/manager/main.go#L186C31-L186C31

Service created for metrics requires name label added on pods.

### Proposed changes

Added "name" label with {{ template "pulumi-kubernetes-operator.name" . }} value to pulumi-kubernetes-operator Deployment at ReplicaSet level.

impact/no-changelog-required

### CODE REVIEW

**Review by dirien — CHANGES_REQUESTED** [review]
Hey @Kris686,

thanks for the PR. Can you bump the minor version in the `Chart.yaml` and add `artifacthub.io/changes:` text?

**Comment by Kris686** [comment]
artifacthub.io/changes: Added "name" label with {{ template "pulumi-kubernetes-operator.name" . }} value to pulumi-kubernetes-operator Deployment at ReplicaSet level.

**Comment by Kris686** [comment]
@dirien done

> Hey @Kris686,
> 
> thanks for the PR. Can you bump the minor version in the `Chart.yaml` and add `artifacthub.io/changes:` text?

**Review by dirien — APPROVED** [review]
LGTM thanks @Kris686 for submitting the PR!

**Pull request merged**
